### ISSUE TITLE
Keep timestamps from original stream

### ISSUE THREAD

**Issue by misiek08** [shaka-project/shaka-streamer#132]
Hello!
I try to work on live streams and provide HA setup. Input is HLS/RTMP (currently HLS, because it's much easier for me).

Input config:
```
inputs:
  - name: https://host/hawe/test/playlist.m3u8
    media_type: video
    extra_input_args: -copyts

  - name: https://host/hawe/test/playlist.m3u8
    media_type: audio
    extra_input_args: -copyts
```

Pipeline config: [pipeline_live_config.yaml](https://github.com/shaka-project/shaka-streamer/blob/main/config_files/pipeline_live_config.yaml)

I've tried to add `-copyts` in multiple places in `transcoder_node.py`, it gets passed to ffmpeg, but does not work. I suspect timestamps get reset because of any of the other flags.

My goal is to run streamer on two different hosts with `$Time$` in segment_template and be able to automatically failover between them. I already found, tried and have working synchronized keyframe cutting points, so that's no problem.
