### ISSUE TITLE
opus not included in hls master file

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-streamer#141]
When I encode the following in the output config file:

```
streaming_mode: vod

# A list of resolutions to encode.
# For VOD, you can specify many more resolutions than you would with live,
# since the encoding does not need to be done in real-time.
resolutions:
  - 1080p
  - 720p
  - 360p

# A list of channel layouts to encode.
channel_layouts:
  - stereo
  - surround

# The codecs to encode with.
audio_codecs:
  - opus
  - aac

video_codecs:
  - h264

# Manifest format (dash, hls or both)
manifest_format:
  - hls

# Length of each segment in seconds.
segment_size: 2

# Forces the use of SegmentTemplate in DASH.
segment_per_file: True
```

The opus is not put on the manifest file of the HLS, here is a manifest example:
```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_2.m3u8",GROUP-ID="default-audio-group",NAME="stream_2",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-STREAM-INF:BANDWIDTH=1525725,AVERAGE-BANDWIDTH=540700,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=24.000,AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5276469,AVERAGE-BANDWIDTH=2141435,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=24.000,AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_0.m3u8
```

As you can see only `aac` got in the master playlist (As far as I understand there is support for Opus in mp4 and in HLS)

**Comment by joeyparrish** [comment]
I believe this is working as intended so long as we put Opus inside WebM.  Most players can't handle WebM in HLS.

I believe we could change Streamer to package Opus inside MP4 instead.  See https://github.com/shaka-project/shaka-streamer/blob/2cee26b9254dbc819ebeae984d38622c4137b544/streamer/bitrate_configuration.py#L64

PRs are always welcome!

**Comment by Chokoabigail** [comment]
Thank you, I'm going to implement it and push PR.

In addition to this, I want to encrypt HLS using a simple `HLS AES128` (i.e. without using all the fency DRM solutions, just encryption and description).

The resulting HLS should look like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="1.m3u8.key",IV=0x00000000000000000000000000000000
#EXTINF:10.000000,
1.ts
...
```

I tried this pipeline:
```
treaming_mode: vod
# since the encoding does not need to be done in real time.
resolutions:
  - 480p
  - 360p

# A list of channel layouts to encode.
channel_layouts:
  - stereo
  - surround

manifest_format:
  - hls

# Length of each segment in seconds.
segment_size: 10

# Forces the use of SegmentTemplate in DASH.
segment_per_file: True

encryption:
  enable: True
  encryption_mode: raw
  keys:
    - key_id: 8858d6731bee84d3b6e3d12f3c767a26
      key: 1ae8ccd0e7985cc0b6203a55855a1034
  clear_lead: 10
```

and the results is not as expected:
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release
#EXT-X-TARGETDURATION:13
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="audio_und_2c_128k_aac_init.mp4"
#EXTINF:10.008,
audio_und_2c_128k_aac_1.mp4
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,iFjWcxvuhNO249EvPHZ6Jg==",KEYFORMAT="identity"
#EXTINF:10.008,
audio_und_2c_128k_aac_2.mp4
```

Which setting I should do to get `#EXT-X-KEY:METHOD=AES-128,URI="1.m3u8.key",IV=0x00000000000000000000000000000000` results?
